plugins {
    id 'groovy'
    id 'com.adarshr.test-logger' apply false
}

apply from: 'test-marker.gradle'
apply plugin: 'com.adarshr.test-logger'

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    testImplementation 'org.apache.groovy:groovy:4.0.26'
    testImplementation 'org.spockframework:spock-core:2.4-groovy-4.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}
